### ISSUE TITLE
php version error

### ISSUE THREAD

**Issue by victor-uy** [gilcot/dwpi#1]
not compatible with php 7.4 
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function syntax_plugin_phpipam::listAddrs(), 1 passed in /var/www/html/wiki/lib/plugins/phpipam/syntax.php on line 1370 and exactly 2 expected in /var/www/html/dokuwiki/lib/plugins/phpipam/syntax.php:890\n
Stack trace:\n#0 /var/www/html/dokuwiki/lib/plugins/phpipam/syntax.php(1370): syntax_plugin_phpipam->listAddrs()\n#1 /var/www/html/dokuwiki/lib/plugins/phpipam/syntax.php(403): syntax_plugin_phpipam->showSub()\n#2

**Comment by gilcot** [comment]
Hello @victor-uy 

Thanks for reporting. I'm not sure it's related to PHP version but to the fact that I hadn't so strict checking (OK it's now fatal whereas not by the past.) I've just made 3 commits that should fix the issue. Unfortunaly, I cannot test it by myself (I'm in a new mission where they don't use phpMyIPAM, and I have no test instance at home) So, can you download the new zip and install it, then let me know if it solves the use for you?

Regards.

**Comment by gilcot** [comment]
No feedback, so I guess it works for you @victor-uy So closing the issue.
